# Postgres
HOST_DB: localhost
PORT_DB: 5440
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: postgres

# MINIO
S3_URL: http://localhost:9000
S3_USER: minioadmin
S3_PASSWORD: minioadmin

# MONGO
MONGO_USER: file_link_hub
MONGO_PASSWORD: password
MONGO_HOST: localhost
MONGO_PORT: 27017


