server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST_DB}:${PORT_DB}/${POSTGRES_DB}?currentSchema=file_link_hub
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: liquibase/changelog.yaml

springdoc:
  swagger-ui:
    path: /docs

s3:
  url: ${S3_URL}
  user: ${S3_USER}
  password: ${S3_PASSWORD}

mongo:
  user: ${MONGO_USER}
  password: ${MONGO_PASSWORD}
  host: ${MONGO_HOST}
  port: ${MONGO_PORT}
  db: file_link_hub

images:
  prefix: new/
