networks:
  agronetwork:
    name: agronetwork
    driver: bridge

services:
  minio:
    image: minio/minio:RELEASE.2024-02-14T21-36-02Z
    container_name: minio
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - agro-s3:/minio
    networks:
      - agronetwork

volumes:
  agro-s3:
