networks:
  agronetwork:
    name: agronetwork
    driver: bridge

services:

  file-link-hub-db:
    networks:
      - agronetwork
    image: postgres:15.1-alpine
    container_name: file-link-hub-db
    env_file:
      - ../.env
    ports:
      - 5440:5432
    volumes:
      - agro-db:/var/lib/postgresql/data/
      - ./init:/docker-entrypoint-initdb.d

volumes:
  agro-db: